export enum NonMedicalObjectType {
	
	BINARY_SENSOR = "BINARY_SENSOR",
	
	SHUTTER = "SHUTTER",
	
	SUNSHINE_SENSOR = "SUNSHINE_SENSOR",
	
	DOOR_SENSOR = "DOOR_SENSOR",
	
	BULB = "BULB",
	
	TEMPERATURE_CONTROLLER = "TEMPERATURE_CONTROLLER",
	
	ALARM_CLOCK = "ALARM_CLOCK",
	
	SMOKE_SENSOR = "SMOKE_SENSOR"
}