DROP TABLE IF EXISTS APPLICATION_PARAMETER;


DROP TABLE IF EXISTS TEMPERATURE_CONTROLLER_SCENARIO;
DROP TABLE IF EXISTS SHUTTER_SCENARIO;
DROP TABLE IF EXISTS ALARM_CLOCK_SCENARIO; 
DROP TABLE IF EXISTS BULB_SCENARIO; 


DROP TABLE IF EXISTS TEMPERATURE_CONTROLLER;
DROP TABLE IF EXISTS SMOKE_SENSOR;
DROP TABLE IF EXISTS SUNSHINE_SENSOR;
DROP TABLE IF EXISTS DOOR_SENSOR;
DROP TABLE IF EXISTS BULB;
DROP TABLE IF EXISTS BINARY_SENSOR;
DROP TABLE IF EXISTS ALARM_CLOCK;
DROP TABLE IF EXISTS SHUTTER;
DROP TABLE IF EXISTS OBJECT_SETTING;
DROP TABLE IF EXISTS REAL_TIME_EVENT;
DROP TABLE IF EXISTS HISTORY_EVENT;
DROP TABLE IF EXISTS NON_MEDICAL_CONNECTED_OBJECT;
DROP TABLE IF EXISTS HEALTH_CONTROL_HISTORY;
DROP TABLE IF EXISTS MEDICAL_CONNECTED_OBJECT;

DROP TABLE IF EXISTS CONNECTED_OBJECT;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS FAILURE;

DROP TABLE IF EXISTS HISTORY_MOVING;
DROP TABLE IF EXISTS ELECTRONIC_TAG;

DROP TABLE IF EXISTS RESIDENT;
DROP TABLE IF EXISTS STAFF;
DROP TABLE IF EXISTS SKYPIEA_USER;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS disease;
DROP TABLE IF EXISTS CLIENT;

